version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    image: cabazurto/cursos-micro-frontend:latest
    pull_policy: never

  micro-curso:
    build:
      context: ./micro-cursos
    image: cabazurto/micro-cursos:latest
    pull_policy: never

  micro-estudiante:
    build:
      context: ./micro-estudiante
    image: cabazurto/micro-estudiante:latest
    pull_policy: never
