version: "3.9"

networks:
  microservices-network:
    driver: bridge

services:
  mysql-micro-curso:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-micro-curso
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_CURSO}
    ports:
      - "${MYSQL_PORT_CURSO}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  mysql-micro-estudiante:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-micro-estudiante
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_ESTUDIANTES}
    ports:
      - "${MYSQL_PORT_ESTUDIANTES}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  micro-curso:
    image: davidrouet/micro-cursos:latest
    container_name: micro-cursos-app
    ports:
      - "${PORT_MICRO_CURSO}:${PORT_MICRO_CURSO}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-micro-curso:3306/${MYSQL_DATABASE_CURSO}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_ROOT_PASSWORD}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      # Si necesitas otras variables de entorno para el microservicio, agrégalas aquí
    depends_on:
      mysql-micro-curso:
        condition: service_healthy
    networks:
      - microservices-network

  micro-estudiante:
    image: davidrouet/micro-estudiantes:latest
    container_name: micro-estudiante
    ports:
      - "${PORT_MICRO_ESTUDIANTE}:${PORT_MICRO_ESTUDIANTE}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-micro-estudiante:3306/${MYSQL_DATABASE_ESTUDIANTES}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_ROOT_PASSWORD}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      mysql-micro-estudiante:
        condition: service_healthy
    networks:
      - microservices-network

  frontend:
    image: davidrouet/cursos-micro-frontend:latest
    container_name: micro-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - microservices-network
    environment:
      # Estas variables se inyectarán en tiempo de build de React (si usas create-react-app)
      - REACT_APP_BACKEND_CURSOS=${REACT_APP_BACKEND_CURSOS}
      - REACT_APP_BACKEND_ESTUDIANTES=${REACT_APP_BACKEND_ESTUDIANTES}
