# docker-compose.override.yml
# Este archivo se aplica automáticamente sobre docker-compose.yml
# Fuerza el uso de imágenes locales en lugar de Docker Hub

version: "3.9"

services:
  # Para frontend, indica que use la imagen local si existe
  frontend:
    pull_policy: never  # Nunca descarga de Docker Hub, usa local
    
  micro-curso:
    pull_policy: never
    
  micro-estudiante:
    pull_policy: never