apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices-app
data:
  MYSQL_DATABASE_CURSO: "microcursos"
  MYSQL_DATABASE_ESTUDIANTES: "estudiantesCurso"
  CORS_ALLOWED_ORIGINS: "*"
