apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-estudiante
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-estudiante
  template:
    metadata:
      labels:
        app: micro-estudiante
    spec:
      containers:
      - name: micro-estudiante
        image: davidrouet/micro-estudiantes:latest
        ports:
        - containerPort: 8002
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-micro-estudiante:3306/estudiantesCurso"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CORS_ALLOWED_ORIGINS