apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-curso-pv
  namespace: microservices-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-curso"