apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-curso-pv
  namespace: microservices-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-curso"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-curso-pvc
  namespace: microservices-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-estudiante-pv
  namespace: microservices-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-estudiante"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-estudiante-pvc
  namespace: microservices-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
